/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedr0ni.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import pedr0ni.models.Musica;
import pedr0ni.sockets.Servidor;

/**
 *
 * @author pedroni
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 7003721892501596084L;
    private Servidor server;
    private DefaultListModel<String> lista;
    private List<Musica> copyLista;
    private Musica[] allMusicas;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame(Servidor server) {
        this.server = server;
        this.copyLista = new ArrayList<Musica>();
        setTitle("ProjetoMusicas - " + server.getSocket().getInetAddress().getHostAddress());
        lista = new DefaultListModel<String>();

        try {
            this.allMusicas = server.getAll();
            for (Musica m : allMusicas) {
                lista.addElement(m.getCantor() + " - " + m.getTitulo() + " (" + m.getEstilo() + ") R$ " + m.getPreco());
                copyLista.add(m);
            }
            initComponents();
            jList1.setModel(lista);
            jList1.setSelectedIndex(0);
        } catch (ClassNotFoundException | IOException e) {
            e.printStackTrace();
        }

        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
            int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
            this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txt_busca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_estilo = new javax.swing.JLabel();
        lbl_cantor = new javax.swing.JLabel();
        lbl_preco = new javax.swing.JLabel();
        lbl_total_selected = new javax.swing.JLabel();
        lbl_desconto = new javax.swing.JLabel();
        lbl_valor_total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_criteria = new javax.swing.JTextField();

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("ProjetoMusicas $total músicas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Músicas"));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                lista.clear();
                copyLista.clear();
                try {
                    if (txt_busca.getText().length() == 0 || txt_criteria.getText().length() == 0) {
                        for (Musica m : server.getAll()) {
                            lista.addElement(
                                    m.getCantor() + " - " + m.getTitulo() + " (" + m.getEstilo() + ") R$ " + m.getPreco());
                            copyLista.add(m);
                        }
                    } else {
                        for (Musica m : server.find(txt_criteria.getText(), txt_busca.getText())) {
                            lista.addElement(
                                    m.getCantor() + " - " + m.getTitulo() + " (" + m.getEstilo() + ") R$ " + m.getPreco());
                            copyLista.add(m);
                        }
                    }
                    
                } catch (ClassNotFoundException | IOException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        txt_busca.setText("Valor para buscar");

        jButton1.setText("BUSCAR");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedr0ni/resources/icon.png"))); // NOI18N

        lbl_titulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_titulo.setText("Titulo: ");

        lbl_estilo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_estilo.setText("Estilo: ");

        lbl_cantor.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_cantor.setText("Cantor: ");

        lbl_preco.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_preco.setText("Preço: ");

        lbl_total_selected.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_total_selected.setText("Músicas Selecionadas: ");

        lbl_desconto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_desconto.setText("Desconto: ");

        lbl_valor_total.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl_valor_total.setText("Valor Total: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_estilo)
                            .addComponent(lbl_cantor)
                            .addComponent(lbl_preco)
                            .addComponent(lbl_total_selected)
                            .addComponent(lbl_desconto)
                            .addComponent(lbl_valor_total)
                            .addComponent(lbl_titulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(lbl_cantor)
                .addGap(18, 18, 18)
                .addComponent(lbl_estilo)
                .addGap(18, 18, 18)
                .addComponent(lbl_preco)
                .addGap(18, 18, 18)
                .addComponent(lbl_total_selected)
                .addGap(18, 18, 18)
                .addComponent(lbl_desconto)
                .addGap(18, 18, 18)
                .addComponent(lbl_valor_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jList1.addListSelectionListener(new ListSelectionListener(){
        
            @Override
            public void valueChanged(ListSelectionEvent e) {
                lbl_titulo.setText("Titulo: " + copyLista.get(jList1.getSelectedIndex()).getTitulo());
            }

        });

        new Timer().scheduleAtFixedRate(new TimerTask(){
        
            @Override
            public void run() {
                lbl_total_selected.setText("Total Selecionado: " + jList1.getSelectedIndices().length);

                int desconto = 0;
                int totalSecs = 0;
                double valor = 0;
                for (int sel : jList1.getSelectedIndices()) {
                    totalSecs += copyLista.get(sel).getDuracao();
                    valor += copyLista.get(sel).getPreco();
                }

                if (totalSecs / 60 >= 30 && totalSecs / 60 < 60) {
                    desconto = 10;
                } else if (totalSecs / 60 >= 60 && totalSecs / 60 < 90) {
                    desconto = 20;
                } else if (totalSecs / 60 >= 90) {
                    desconto = 30;
                }

                valor = valor - ((desconto / 100) * valor);

                lbl_desconto.setText("Desconto: " + desconto + "% (" + totalSecs / 60 + " mins)");

                lbl_valor_total.setText("Valor Total: R$ " + Double.valueOf(new DecimalFormat("#.##").format(valor)));
            }
        }, 0, 250L);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Ações");

        txt_criteria.setText("Criterio de busca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_criteria, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_criteria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantor;
    private javax.swing.JLabel lbl_desconto;
    private javax.swing.JLabel lbl_estilo;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_total_selected;
    private javax.swing.JLabel lbl_valor_total;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_criteria;
    // End of variables declaration//GEN-END:variables
}
